### ISSUE TITLE
Question about the SoftAttnDepth

### ISSUE THREAD

**Issue by Bai-YunHan** [sjsu-smart-lab/Self-supervised-Monocular-Trained-Depth-Estimation-using-Self-attention-and-Discrete-Disparity-Volum#1]
Hi, 

First, thank you for your effort in reproducing this work.

I have a question regarding the SoftAttnDepth in networks/decoder.py.

In networks/decoder.py, there's a comment  at line 60 :  
    # The wokring ones uses: 0.01 and 1.0
Then, if the ‘alpha' is set to 0.01 (instead of 0), then the max depth is only 10m.
    Given, min_disp, max_disp = 1/100, 1/0.1
    max depth = min_disp + (max_disp - min_disp)*alpha 
    max depth = 1/(0.01 + (10 - 0.01)*alpha)
However the paper suggests that it could predict up to 80m.

Since, your report on open-review mentioned you contacted the author and asked them about the implementation of DDV.
So, I’d like to know, does the author also set the ‘alpha’ to 0.01 instead of 0 in order to make it work?

Thank you very much!

**Comment by Sanjana7395** [comment]
Hi Bai-YunHan,

In network/decoder.py at line 151, alpha is set to 0.001 which overrides 0.01.  So the max_depth will be 50m.

This is as per the code snippet provided by the authors. Also refer [DORN](https://arxiv.org/pdf/1806.02446.pdf) from which the concept of ordinal regression for the decoder is adopted. DORN shows better results on KITTI dataset with 50m than with 80m.

Regret the error in the text. Will make the necessary changes.
Thanks and regards,
Sanjana

**Comment by Bai-YunHan** [comment]
Thank you for your reply Sanjana, this is very helpful.

Best regards,
YunHan
